version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=dynamic-db
      - POSTGRES_USER=dynamic-app
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  dynamic-table:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: