# Generated by Django 5.0.4 on 2024-04-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmodelmetadata',
            name='fields',
            field=models.JSONField(null=True),
        ),
    ]
